Create Card component
Filin1985/ts_next_project pull request #2
Opened 2023-08-05 14:15 UTC by Filin1985

2023-08-09 05:47 UTC, Grinv requested changes

2023-08-09 05:47 UTC, Grinv commented on app/page.tsx
> +      {/* <Button appearance='primary' type='button' arrow='right'>
Лучше не оставлять в коде лишний мусор и закомментированный код. Только если он не супер важен.
А если супер важен, то лучше оставлять выше комментарий, почему.
Например: 'Раскомментировать, когда доделаем задачу N'

2023-08-09 05:47 UTC, Grinv commented on app/globals.css
> +  background: #f5f6f8;
Можно тоже вынести в css переменную :)

2023-08-09 05:47 UTC, Grinv commented on app/layout.tsx
> +      <body className={noto.className}>{children}</body>
Советую шрифт записать в css переменную и применить к body в globals.css
Возможно она нам где-то в будущем ещё понадобится
Пример как сделать: https://nextjs.org/docs/pages/api-reference/components/font#css-variables

2023-08-09 05:47 UTC, Grinv commented on components/Button/Button.tsx
> +    <button
Можно немного читабельнее сделать код :)
```javascript
const classes = cn(styles.button, className, {
  [styles.primary]: appearance === 'primary',
  [styles.ghost]: appearance === 'ghost',
});

return (
  <button {...props} className={classes}>
    // ...
  </button>
);

2023-08-09 05:47 UTC, Grinv commented on components/Button/Button.tsx
> +      {...props}
Со спрэдами нужно быть очень аккуратным и лучше спрэды писать первыми, потому что внутри props может быть className, которым перезатрёт твой заданный и это не так просто будет отдебажить)
```javascript
<button {...props} className={classes}>

2023-08-09 05:47 UTC, Grinv commented on components/Button/Button.tsx
> +      {arrow !== 'none' && (
Зачем none? Можно передавать `showArrow`, как булевое значение например

2023-08-09 05:47 UTC, Grinv commented on components/Button/Button.tsx
> +      {arrow !== 'none' && (
Как мне кажется, название компонента `Button` говорит нам о том, что это некая абстрактная кнопка, в которой может быть любая иконка. Так давай оставим возможность применять любую кнопку.
Можем передавать внутрь кнопки, как пропс
Если хочется оставить как специфическую кнопку, то лучше переименовать. Например `ButtonWithArrow`. А то появится ещё одна кнопка. Как назовём? `Button2`? :)

2023-08-09 05:47 UTC, Grinv commented on components/Button/Button.tsx
> +        <span
span тут не нужен. Вообще лучше стараться делать меньше вложенностей. Это хорошо сказывается на производительности.
```javascript
<ArrowIcon className={cn(...)} />

2023-08-09 05:47 UTC, Grinv commented on components/Card/Card.module.css
> +  color: var(--c-black, #2c2c2c);
Зачем тут вторая переменная?

2023-08-09 05:47 UTC, Grinv commented on components/Card/Card.module.css
> +  color: #1473e6;
В переменную

2023-08-09 05:47 UTC, Grinv commented on components/Tag/Tag.tsx
> +      {href ? <a href={href}>{children}</a> : <>{children}</>}
Супер неочевидное поведение с ссылкой.

Если у тебя тэг может быть либо просто контейнером, либо ссылкой, либо кнопкой (может тебе надо будет применить onClick), я бы сделал так:
```javascript
const className = cn(styles.tag, className, {
  [styles.s]: size === 's',
  [styles.m]: size === 'm',
  [styles.ghost]: color === 'ghost',
  [styles.red]: color === 'red',
  [styles.gray]: color === 'gray',
  [styles.green]: color === 'green',
  [styles.primary]: color === 'primary',
});

const propsWithClass = { ...props, className };

if (props.href) {
  return <a {...props}>{children}</a>;
}

if (props.onClick) {
  return <button {...props}>{children}</button>;
}

return <span {...props}>{children}</span>;

2023-08-09 05:47 UTC, Grinv commented on components/Card/Card.tsx
> +    <div className={styles.container}>
Лучше использовать для карточек тэг `article`

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/article
>Examples include: a forum post, a magazine or newspaper article, or a blog entry, a product card, a user-submitted comment, an interactive widget or gadget, or any other independent item of content.

Вообще хорошая привычка использовать семантически правильные тэги. Сначала подумай, какой тэг наиболее подходящий. И если уже совсем ничего не подходит, то тогда используй `div` или `span` :)

2023-08-09 11:41 UTC, Filin1985 commented on components/Button/Button.tsx
> +      {...props}
Круто, не  обращал внимание на это! Спасибо

2023-08-09 11:50 UTC, Filin1985 commented on components/Card/Card.module.css
> +  color: var(--c-black, #2c2c2c);
Случайно)

2023-08-09 12:22 UTC, Filin1985 commented on components/Card/Card.tsx
> +    <div className={styles.container}>
С этим полностью согласен, вылетело из головы(

2023-08-09 12:28 UTC, Filin1985 commented on components/Button/Button.tsx
> +      {arrow !== 'none' && (
там типа не булевое значение, а может принимать разный вид стрелки, она может быть направлена вниз или вправо

2023-08-12 11:20 UTC, Grinv approved these changes

2023-08-12 11:20 UTC, Grinv commented on app/layout.tsx
> +    <html lang='en'>
У нас весь контент на русском, поэтому хорошо бы тут использовать `lang='ru'`, но тогда хорошо бы исправить и title с description и перевести на русский, чтобы бы консинствентно.

2023-08-12 11:20 UTC, Grinv commented on components/ButtonWithArrow/ButtonWithArrow.tsx
> +      {arrow !== 'none' && (
Я думаю, none тут лишнее. Можно просто ничего не передавать.
Тогда мы можем написать просто
```javascript
{Boolean(arrow) && (
   <ArrowIcon
      className={cn(styles.arrow, {
          [styles.down]: arrow === 'down',
      })}
   />
 )}

2023-08-12 11:20 UTC, Grinv commented on components/Card/Card.tsx
> +import screenPicture from '../../images/screen.png';
Лучше все иконки и картинки хранить в public.
И сделать алиас, чтоб мы могли импортить вот так:
```javascript
import screenPicture from '@/public/images/screen.png';

2023-08-12 11:20 UTC, Grinv commented on components/Like/Like.tsx
> +      <p className={styles.tagTime}>4</p>
Почему p? Это не текст, не законченое предложение)

2023-08-12 11:20 UTC, merged