2 components
Filin1985/ts_next_project pull request #4
Opened 2023-08-13 13:21 UTC by Filin1985

2023-08-17 06:58 UTC, Grinv requested changes

2023-08-17 06:58 UTC, Grinv commented on app/(site)/components/Header/Header.tsx
> +            <GithubIcon />
Иконки, которые достаточно большие и в которых не надо менять цвет - лучше вставлять через Image.
Так мы сократим размер html и лучше будет работать кеширование

2023-08-17 06:58 UTC, Grinv commented on app/(site)/components/Header/Header.tsx
> +import GithubIcon from './github.svg'
Лучше все файлы класть в public
`/public/icons`
`/public/images`
`/public/pdf`

2023-08-17 06:58 UTC, Grinv commented on app/(site)/layout.tsx
>      <html lang='en'>
У нас же весь текст на русском. Почему en?)

2023-08-17 06:58 UTC, Grinv commented on app/(site)/layout.tsx
>    weight: ['300', '400', '500', '700'],
Нам точно нужны все эти weight?

2023-08-17 06:58 UTC, Grinv commented on app/(site)/page.tsx
> +      <div className={styles.wrapper}>
Кажется, нам не нужен этот div и класс можно накинуть на main
Старайся делать минимальное количество элементов и вложенностей. Так лучше будет оптимизация

2023-08-17 06:58 UTC, Grinv commented on components/Card/Card.tsx
>  import screenPicture from '../../images/screen.png';
Давай сделаем alias для public, чтоб можно было обращаться через `/public/images/screen.png`

2023-08-17 06:58 UTC, Grinv commented on components/Card/Card.tsx
>        <div className={styles.imageContainer}>
Тут нужен div? Можно класс и на картинку накинуть

2023-08-17 06:58 UTC, Grinv commented on components/Like/Like.tsx
> +import React, { useEffect, useState } from 'react';
Не нужно импортировать React

2023-08-17 06:58 UTC, Grinv commented on components/Like/Like.tsx
> +  const changeLikeOnServer = async () => {
Давай вынесем функция за компонент и будем передавать itemId, как аргумент. Она у нас не меняется и нет смысла пересоздавать каждый раз при вызове компонента

2023-08-17 06:58 UTC, Grinv commented on components/Like/Like.tsx
> +      setLikes(likes + 1);
Ммм. Я понимаю, что заглушка, но на будущее не забывай, что тебе надо и на бэкенд посылать новые данные, а не только локальный стор менять.

2023-08-17 06:58 UTC, Grinv commented on components/Like/Like.tsx
> +      setLikes(likes + 1);
Опять же, если мы завязаны на прошлых данных их state, не забывай, что он асинхронный и лучше завязываться на предыдущее значение
```javascript
setLikes(prevLikesState => prevLikesState + 1);

2023-08-17 06:58 UTC, Grinv commented on components/Like/Like.tsx
> +      setLikes(likes + 1);
А вообще, нужно ли нам менять state?
Можно сделать так:
```javascript
setIsLiked(prevState => !prevState);
```
и просто отображать так: 
```javascript
<div className={styles.likesAmount}>{isLiked ? likes + 1 : isLiked}</div>
```
Тогда не надо будет обновлять setLikes на каждый клик

2023-08-17 06:58 UTC, Grinv commented on components/Like/Like.tsx
> +      <p className={styles.tagTime}>{likes}</p>
Это точно не параграф
p используем для законченных полноценных предложений
тут просто используй div или span

2023-08-17 06:58 UTC, Grinv commented on app/(site)/components/Header/Header.module.css
> +  color: #000;
Раз уж вынес в css перемененные) 
```css
color: var(--black);

2023-08-17 06:58 UTC, Grinv commented on components/Like/Like.tsx
> +      <p className={styles.tagTime}>{likes}</p>
почему `.tagTime`?) Это больше `.likesAmount`

2023-08-21 04:57 UTC, Filin1985 commented on components/Like/Like.tsx
> +      setLikes(likes + 1);
Так проще конечно))

2023-08-22 02:37 UTC, Filin1985 commented on app/(site)/components/Header/Header.tsx
> +            <GithubIcon />
Не получилось решить проблему с svg, не хочет есть их как src в Image

2023-08-24 23:37 UTC, Grinv commented on app/(site)/components/Header/Header.tsx
> +            <GithubIcon />
У svgr же прям на оф сайте есть дока, как подключить в nextjs :)
https://react-svgr.com/docs/next/#usage
Если что, задавай вопросы в дискорде в чат или личку, помогу)

2023-08-25 00:01 UTC, Grinv requested changes

2023-08-25 00:01 UTC, Grinv commented on components/Like/Like.tsx
>      <div className={styles.tagLike}>
Я бы вообще всё это сделал одной большой кнопкой)
Так и пальцем легче попасть, а значит и количество лайков вырастет и маркетологи довольны будут)

2023-08-25 00:01 UTC, Grinv commented on next.config.js
> +
так, а что не получилось? Напиши либо в чате "вопрос наставнику", либо мне в личку, разберёмся

2023-08-27 12:27 UTC, Grinv requested changes

2023-08-27 12:27 UTC, Grinv commented on README.md
> +NEXT_PUBLIC_DOMAIN=https://jsonplaceholder.typicode.com/
Молодец)

2023-08-27 12:27 UTC, Grinv commented on app/(site)/layout.tsx
> +      <body className={noto.className}>
Не поменял на `className={noto.variable}`
Не забудь сделать в следующем PR

2023-08-27 12:27 UTC, Grinv commented on app/(site)/layout.tsx
>    subsets: ['latin'],
Так cyrillic и не добавил.
Нажимай Resolve conversation только когда точно уже поправил и сохранил

2023-08-27 12:47 UTC, Grinv approved these changes

2023-08-27 12:47 UTC, Grinv commented on components/Card/Card.tsx
> +          <a href='#' className={styles.tagTime}>Читать</a>
Лучше пользовать всё-таки использовать возможности некста и для ссылок применять компонент `next/link`

2023-08-27 12:47 UTC, Grinv commented on components/Like/Like.tsx
> +      : setLikes((prevLikesState) => prevLikesState + 1);
```jsx
setLikes((prevLikesState) => isLiked ? prevLikesState - 1 : prevLikesState - 1);

2023-08-27 12:47 UTC, Grinv commented on components/Card/Card.tsx
> +import { Tag, Pgraph, Htag } from '..';
Так немного читабельнее
```javascript
import { Tag, Pgraph, Htag } from '@/components';

2023-08-27 12:47 UTC, merged